version: '3.8'

services:
  client:
    container_name: client
    image: client
    ports:
      - 80:80

    depends_on:
      - server

    healthcheck:
      test: service nginx status || exit 1
      interval: 15s
      timeout: 5s
      retries: 3

  server:
    container_name: server
    image: server
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_health

    environment:
      - ENVIRONMENT=docker

    healthcheck:
      test: wget localhost:3333/api/v1/health -q -O - > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # postgres:
  #   container_name: postgres
  #   image: postgres:alpine
  #   ports:
  #     - 4700:5432
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USERNAME}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_DB=${DATABASE_NAME}
  #   healthcheck:
  #     test: ["CMD-SHELL",  "su -c 'pg_isready -U postgres' postgres"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3