services:
  - type: web
    name: hba-client
    repo: https://github.com/MCesarczyk/home-budget-assistant
    env: docker
    plan: free
    dockerfilePath: ./apps/client/Dockerfile.render
    dockerContext: ./

  - type: web
    name: hba-server
    repo: https://github.com/MCesarczyk/home-budget-assistant
    env: docker
    plan: free
    dockerfilePath: ./apps/server/Dockerfile.render
    dockerContext: ./

databases:
  - name: hba-db
    plan: free