FROM node:latest AS build-stage

WORKDIR /app

COPY package*.json /app/
COPY pnpm-lock.yaml /app/

RUN npm install pnpm -g

RUN pnpm install --frozen-lockfile

COPY ./ /app/

ARG configuration=production

RUN npx nx run client:build:render


FROM nginxinc/nginx-unprivileged


COPY --from=build-stage /app/dist/apps/client/browser /usr/share/nginx/html
COPY apps/client/nginx-render.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80
